version: "3"

services:
  # cde-app:
  #   image: cde-app
  #   stdin_open: true
  #   ports:
  #     - "3000:3000"
  # networks:
  #   - mern-app

  cde-api-server:
    image: cde-api-server
    restart: always
    ports:
      - "5000:5000"
    # networks:
    #   - mern-app
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    # expose:
    #   - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=""
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=blueocean2
    # networks:
    #   - mern-app
    volumes:
      - data:/data/db

# networks:
#   mern-app:
#     driver: bridge

volumes:
  data:
    # driver: local
